# Generated by Django 5.1.6 on 2025-05-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseyoga',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
