# Generated by Django 5.1.6 on 2025-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_claseyoga_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseyoga',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
